services:
  uc8q4m2x7v:
    container_name: uc8q4m2x7v_app
    image: ghcr.io/mr-devloper005/uplandcommerce.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3085:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
